/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.nhom3_quanlyphonggyms.view;
import com.mycompany.nhom3_quanlyphonggyms.controller.RoomController;
import com.mycompany.nhom3_quanlyphonggyms.controller.TrainerController;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author PC
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    
    
    
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnChooseSpecialPerson = new javax.swing.JButton();
        btnChooseResidents = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnChooseRoom = new javax.swing.JButton();
        btnChooseTrainer = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html>Quản lý tình hình dân cư<br> ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(960, 679));

        btnChooseSpecialPerson.setBackground(new java.awt.Color(0, 0, 102));
        btnChooseSpecialPerson.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnChooseSpecialPerson.setForeground(new java.awt.Color(255, 255, 255));
        btnChooseSpecialPerson.setText("<html><div style='text-align: center;'>Quản lý các đối tượng đặc biệt<br></div>");
        btnChooseSpecialPerson.setToolTipText("");
        btnChooseSpecialPerson.setBorder(null);
        btnChooseSpecialPerson.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChooseSpecialPerson.setOpaque(true);
        btnChooseSpecialPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseSpecialPersonActionPerformed(evt);
            }
        });

        btnChooseResidents.setBackground(new java.awt.Color(0, 0, 102));
        btnChooseResidents.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnChooseResidents.setForeground(new java.awt.Color(255, 255, 255));
        btnChooseResidents.setText("<html><div style='text-align: center;'>Quản lý dân cư<br></div>");
        btnChooseResidents.setToolTipText("");
        btnChooseResidents.setBorder(null);
        btnChooseResidents.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChooseResidents.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChooseResidents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseResidentsActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("<html>Quản lý phòng GYM DLT<br> ");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnChooseRoom.setBackground(new java.awt.Color(0, 0, 102));
        btnChooseRoom.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnChooseRoom.setForeground(new java.awt.Color(255, 255, 255));
        btnChooseRoom.setText("<html><div style='text-align: center;'>Quản lý phòng tập<br></div>");
        btnChooseRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseRoomActionPerformed(evt);
            }
        });

        btnChooseTrainer.setBackground(new java.awt.Color(0, 0, 102));
        btnChooseTrainer.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnChooseTrainer.setForeground(new java.awt.Color(255, 255, 255));
        btnChooseTrainer.setText("Quản lý huấn luyện viên");
        btnChooseTrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseTrainerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChooseResidents, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChooseRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnChooseSpecialPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnChooseTrainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChooseResidents, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChooseSpecialPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChooseRoom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChooseTrainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseSpecialPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseSpecialPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChooseSpecialPersonActionPerformed

    private void btnChooseResidentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseResidentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChooseResidentsActionPerformed

    private void btnChooseRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseRoomActionPerformed
        // TODO add your handling code here:
        RoomView roomView = new RoomView();
        RoomController controller = new RoomController(roomView, this); // đúng!
        controller.showRoomView();
        this.setVisible(false);
    }//GEN-LAST:event_btnChooseRoomActionPerformed

    private void btnChooseTrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseTrainerActionPerformed
        // TODO add your handling code here:
        TrainerView trainerView = new TrainerView();
        new TrainerController(trainerView, this);
        trainerView.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnChooseTrainerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }
    
    public void addChooseSpecialPersonListener(ActionListener listener){
        btnChooseSpecialPerson.addActionListener(listener);
    }
    
    public void addChooseResidentsListener(ActionListener listener){
        btnChooseResidents.addActionListener(listener);
    }
    
    public void addChooseRoomListener(ActionListener listener) {
        btnChooseRoom.addActionListener(listener);
    }
    public void addChooseTrainerListener(ActionListener listener) {
        btnChooseTrainer.addActionListener(listener);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseResidents;
    private javax.swing.JButton btnChooseRoom;
    private javax.swing.JButton btnChooseSpecialPerson;
    private javax.swing.JButton btnChooseTrainer;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
