/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.nhom3_quanlyphonggyms.view;
import com.mycompany.nhom3_quanlyphonggyms.controller.RoomController;
import com.mycompany.nhom3_quanlyphonggyms.controller.TrainerController;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author PC
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    
    
    
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnChooseExerciseType = new javax.swing.JButton();
        btnChooseMember = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnChooseRoom = new javax.swing.JButton();
        btnChooseTrainer = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html>Quản lý tình hình dân cư<br> ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(960, 679));

        btnChooseExerciseType.setBackground(new java.awt.Color(0, 0, 102));
        btnChooseExerciseType.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnChooseExerciseType.setForeground(new java.awt.Color(255, 255, 255));
        btnChooseExerciseType.setText("<html><div style='text-align: center;'>Quản lý loại hình<br></div>");
        btnChooseExerciseType.setToolTipText("");
        btnChooseExerciseType.setBorder(null);
        btnChooseExerciseType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChooseExerciseType.setOpaque(true);
        btnChooseExerciseType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseExerciseTypeActionPerformed(evt);
            }
        });

        btnChooseMember.setBackground(new java.awt.Color(0, 0, 102));
        btnChooseMember.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnChooseMember.setForeground(new java.awt.Color(255, 255, 255));
        btnChooseMember.setText("<html><div style='text-align: center;'>Quản Lý học viên<br></div>");
        btnChooseMember.setToolTipText("");
        btnChooseMember.setBorder(null);
        btnChooseMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChooseMember.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChooseMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseMemberActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("<html><div style=\"text-align: center;\">\n    <h1>QUẢN LÝ PHÒNG GYM DLT</h1>\n</div>\n");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnChooseRoom.setBackground(new java.awt.Color(0, 0, 102));
        btnChooseRoom.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnChooseRoom.setForeground(new java.awt.Color(255, 255, 255));
        btnChooseRoom.setText("<html><div style='text-align: center;'>Quản lý phòng tập<br></div>");
        btnChooseRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseRoomActionPerformed(evt);
            }
        });

        btnChooseTrainer.setBackground(new java.awt.Color(0, 0, 102));
        btnChooseTrainer.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btnChooseTrainer.setForeground(new java.awt.Color(255, 255, 255));
        btnChooseTrainer.setText("Quản lý huấn luyện viên");
        btnChooseTrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseTrainerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnChooseRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChooseMember, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChooseTrainer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnChooseExerciseType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnChooseTrainer, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChooseMember, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChooseRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChooseExerciseType, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseExerciseTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseExerciseTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChooseExerciseTypeActionPerformed

    private void btnChooseMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChooseMemberActionPerformed

    private void btnChooseRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseRoomActionPerformed
        // TODO add your handling code here:
        RoomView roomView = new RoomView();
        RoomController controller = new RoomController(roomView, this); // đúng!
        controller.showRoomView();
        this.setVisible(false);
    }//GEN-LAST:event_btnChooseRoomActionPerformed

    private void btnChooseTrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseTrainerActionPerformed
        // TODO add your handling code here:
        TrainerView trainerView = new TrainerView();
        new TrainerController(trainerView, this);
        trainerView.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnChooseTrainerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }
    
    public void addChooseRoomListener(ActionListener listener) {
        btnChooseRoom.addActionListener(listener);
    }
    public void addChooseTrainerListener(ActionListener listener) {
        btnChooseTrainer.addActionListener(listener);
    }
    public void addChooseMemberListener(ActionListener listener) {
        btnChooseMember.addActionListener(listener);
    }
    public void addChooseExerciseTypeListener(ActionListener listener) {
        btnChooseExerciseType.addActionListener(listener);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseExerciseType;
    private javax.swing.JButton btnChooseMember;
    private javax.swing.JButton btnChooseRoom;
    private javax.swing.JButton btnChooseTrainer;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
